name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        # - Install msttcorefonts, so we have the Verdana font available for diagram generation
        # - Install graphviz, so we have the dot binary available for diagram generation
        run: |-
          sudo apt-get update
          echo msttcorefonts msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer
          sudo apt-get install -y graphviz
          sudo apt-get install -y build-essential libz-dev

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25.0.1'
          server-id: central
          gpg-private-key: ${{ secrets.PGP_KEY }}
          gpg-passphrase: PGP_KEY_PASSWORD
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          overwrite-settings: false

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and release to Maven Central
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Required for reactor dependencies
          mvn -B clean install -DskipTests
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.release_version }}
          mvn -B versions:commit

          # Actual build
          mvn -B clean deploy -Ddownload-nodejs,download-antora,release
        shell: bash
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # 2.6.1
        with:
          body: "Release version ${{ github.event.inputs.release_version }}"
          tag_name: v${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
          files: |
            cool-rdf/cli/target/cool-rdf-cli-${{ github.event.inputs.release_version }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: docs/target/build/site
